spring.application.name=gestion_pedidos

spring.datasource.url=jdbc:postgresql://localhost:5432/gestion_pedidos
spring.datasource.username=postgres
spring.datasource.password=Tupapi_4321

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true